[package]
name = "Darkeye"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["cargo"] }
colored = "2.1.0"
reqwest = "0.12.4"
serde = "1.0.202"
serde_json = "1.0.117"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
